/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Latihan;

/**
 *
 * @author hapiz
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    int hargaPerHari = 0;
    int jumlahHari = 0;
    String jenisPS = "";
    String durasi = "";
    String jk = "";
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JKL = new javax.swing.JRadioButton();
        JKP = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        JenisBarang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Durasi = new javax.swing.JComboBox<>();
        Cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA      :");

        jLabel2.setText("ALAMAT  :");

        jLabel3.setText("Usia          :");

        jLabel4.setText("Jenis Kelamin :");

        JKL.setText("Laki - Laki");
        JKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKLActionPerformed(evt);
            }
        });

        JKP.setText("Perempuan");
        JKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKPActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Barang   :");

        JenisBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PS 1", "PS 2", "PS 3", "PS 4", "PS 5" }));
        JenisBarang.setSelectedIndex(-1);
        JenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisBarangActionPerformed(evt);
            }
        });

        jLabel6.setText("Durasi              :");

        Durasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 HARI", "2 HARI", "3 HARI", "4 HARI", "5 HARI", "6 HARI", "7 HARI" }));
        Durasi.setSelectedIndex(-1);
        Durasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurasiActionPerformed(evt);
            }
        });

        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        Output.setColumns(20);
        Output.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Output.setRows(5);
        jScrollPane1.setViewportView(Output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addGap(15, 15, 15))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtUsia, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                        .addComponent(txtNama)
                                        .addComponent(txtAlamat)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(JKL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JKP))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(JenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(Cetak))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JKL)
                    .addComponent(JKP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Cetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JKLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKLActionPerformed
        // TODO add your handling code here:
        jk = "Laki - Laki";
        JKP.setSelected(false);
    }//GEN-LAST:event_JKLActionPerformed

    private void JKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKPActionPerformed
        // TODO add your handling code here:
        jk = "Perempuan";
        JKL.setSelected(false);
    }//GEN-LAST:event_JKPActionPerformed

    private void JenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisBarangActionPerformed
        // TODO add your handling code here:
        int indexPS = JenisBarang.getSelectedIndex();
        if (indexPS == 0){
            jenisPS = "PS 1";
            hargaPerHari = 30000;
        } else if (indexPS == 1){
            jenisPS = "PS 2";
            hargaPerHari = 50000;
        } else if (indexPS == 2){
            jenisPS = "PS 3";
            hargaPerHari = 60000;
        } else if (indexPS == 3){
            jenisPS = "PS 4";
            hargaPerHari = 100000;
        } else if (indexPS == 4){
            jenisPS = "PS 5";
            hargaPerHari = 300000;
        }
    }//GEN-LAST:event_JenisBarangActionPerformed

    private void DurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurasiActionPerformed
        // TODO add your handling code here:
        int indexDurasi = Durasi.getSelectedIndex();
        if (indexDurasi == 0){
            durasi = "1 Hari";
            jumlahHari = 1;
        } else if (indexDurasi == 1){
            durasi = "2 Hari";
            jumlahHari = 2;
        } else if (indexDurasi == 2){
            durasi = "3 Hari";
            jumlahHari = 3;
        } else if (indexDurasi == 3){
            durasi = "4 Hari";
            jumlahHari = 4;
        } else if (indexDurasi == 4){
            durasi = "5 Hari";
            jumlahHari = 5;
        }else if (indexDurasi == 5){
            durasi = "6 Hari";
            jumlahHari = 6;
        }else if (indexDurasi == 6){
            durasi = "7 Hari";
            jumlahHari = 7;
        }
    }//GEN-LAST:event_DurasiActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String usia = txtUsia.getText();
        
        if (!usia.matches("\\d+")){
        javax.swing.JOptionPane.showMessageDialog(null, "Usia Harus Berupa Angka Cuy!!!");
        txtUsia.requestFocus();
        return;
        }
        int total = hargaPerHari * jumlahHari;

        Output.setText(
        "========== STRUK ==========\n" +
        "Nama           : " + nama + "\n" +
        "Alamat         : " + alamat + "\n" +
        "Usia           : " + usia + "\n" +
        "Jenis Kelamin  : " + jk + "\n" +
        "Jenis PS       : " + jenisPS + "\n" +
        "Durasi         : " + durasi + "\n" +
        "Harga / Hari   : Rp " + hargaPerHari + "\n" +
        "Total Harga    : Rp " + total + "\n" +
        "=========================="
        );
    }//GEN-LAST:event_CetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cetak;
    private javax.swing.JComboBox<String> Durasi;
    private javax.swing.JRadioButton JKL;
    private javax.swing.JRadioButton JKP;
    private javax.swing.JComboBox<String> JenisBarang;
    private javax.swing.JTextArea Output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
