/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Latihan;

/**
 *
 * @author hapiz
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    String kelas;
    int harga;
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pilih = new javax.swing.JLabel();
        KelasA = new javax.swing.JRadioButton();
        KelasB = new javax.swing.JRadioButton();
        TombolCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Outputnya = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pilih.setText("Pilih :");

        KelasA.setText("Kelas A");
        KelasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasAActionPerformed(evt);
            }
        });

        KelasB.setText("Kelas B");
        KelasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasBActionPerformed(evt);
            }
        });

        TombolCetak.setText("Cetak");
        TombolCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolCetakActionPerformed(evt);
            }
        });

        Outputnya.setColumns(20);
        Outputnya.setRows(5);
        jScrollPane1.setViewportView(Outputnya);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TombolCetak)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pilih)
                        .addGap(39, 39, 39)
                        .addComponent(KelasA)
                        .addGap(36, 36, 36)
                        .addComponent(KelasB)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pilih)
                    .addComponent(KelasA)
                    .addComponent(KelasB))
                .addGap(18, 18, 18)
                .addComponent(TombolCetak)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolCetakActionPerformed
        // TODO add your handling code here:
        Outputnya.setText("Kelas: " +kelas +"\nHarga: "+harga);
    }//GEN-LAST:event_TombolCetakActionPerformed

    private void KelasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasAActionPerformed
        // TODO add your handling code here:
        kelas = KelasA.getText();
        harga = 100000;
        KelasB.setSelected(false);
    }//GEN-LAST:event_KelasAActionPerformed

    private void KelasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasBActionPerformed
        // TODO add your handling code here:
        kelas = KelasB.getText();
        harga = 100000;
        KelasA.setSelected(false);
    }//GEN-LAST:event_KelasBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton KelasA;
    private javax.swing.JRadioButton KelasB;
    private javax.swing.JTextArea Outputnya;
    private javax.swing.JLabel Pilih;
    private javax.swing.JButton TombolCetak;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
